// Subtitle.swift
// Represents subtitle/caption information for video content
// Supports various subtitle formats and languages

import Foundation

/// Represents a subtitle track for video content
struct Subtitle: Equatable, Identifiable, Codable {
  /// Unique identifier for the subtitle
  let id: String
  
  /// Display name for the subtitle (e.g., "English", "Spanish", "French")
  let name: String
  
  /// Language code (e.g., "en", "es", "fr")
  let language: String
  
  /// URL to the subtitle file
  let url: String
  
  /// Subtitle format (e.g., "vtt", "srt", "ass")
  let format: SubtitleFormat
  
  /// Whether this subtitle is auto-generated
  let isAutoGenerated: Bool
  
  /// Whether this subtitle includes hearing impaired descriptions
  let isHearingImpaired: Bool
  
  /// Additional metadata
  let metadata: [String: String]?
  
  init(
    id: String,
    name: String,
    language: String,
    url: String,
    format: SubtitleFormat = .vtt,
    isAutoGenerated: Bool = false,
    isHearingImpaired: Bool = false,
    metadata: [String: String]? = nil
  ) {
    self.id = id
    self.name = name
    self.language = language
    self.url = url
    self.format = format
    self.isAutoGenerated = isAutoGenerated
    self.isHearingImpaired = isHearingImpaired
    self.metadata = metadata
  }
}

/// Supported subtitle formats
enum SubtitleFormat: String, CaseIterable, Codable {
  case vtt = "vtt"
  case srt = "srt"
  case ass = "ass"
  case ssa = "ssa"
  case ttml = "ttml"
  
  /// Display name for the format
  var displayName: String {
    switch self {
    case .vtt: return "WebVTT"
    case .srt: return "SubRip"
    case .ass: return "Advanced SubStation Alpha"
    case .ssa: return "SubStation Alpha"
    case .ttml: return "Timed Text Markup Language"
    }
  }
  
  /// MIME type for the format
  var mimeType: String {
    switch self {
    case .vtt: return "text/vtt"
    case .srt: return "text/srt"
    case .ass: return "text/ass"
    case .ssa: return "text/ssa"
    case .ttml: return "application/ttml+xml"
    }
  }
}

// MARK: - Extensions

extension Subtitle {
  /// Creates a "None" subtitle option for disabling subtitles
  static var none: Subtitle {
    Subtitle(
      id: "none",
      name: "None",
      language: "none",
      url: "",
      format: .vtt
    )
  }
  
  /// Creates an "Auto" subtitle option for automatic subtitle selection
  static var auto: Subtitle {
    Subtitle(
      id: "auto",
      name: "Auto",
      language: "auto",
      url: "",
      format: .vtt,
      isAutoGenerated: true
    )
  }
  
  /// Whether this is a special subtitle option (None or Auto)
  var isSpecialOption: Bool {
    return id == "none" || id == "auto"
  }
  
  /// Display name with additional info
  var displayNameWithInfo: String {
    var components = [name]
    
    if isAutoGenerated && !isSpecialOption {
      components.append("(Auto)")
    }
    
    if isHearingImpaired {
      components.append("(CC)")
    }
    
    return components.joined(separator: " ")
  }
}